### PR TITLE
Setup/devise

### PR DESCRIPTION
**Pull request by M-AminAlizadeh**
The things that were done in this PR:

- Install & setup `devise`
 
I do more commits than my partners because I wadsthe driver and he was the navigator
And want to learn more about devise

### CODE REVIEW

**Review by abdulhamiid — COMMENTED** [review]
Hi Team 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ ❌ 

- [ ] This milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#work-and-submission-mode). 

- [x] Please ensure that your partner has a significant contribution and everyone has contributed equally to the project you're reviewing, 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by joel-kalema — COMMENTED** [review]
Hi TEAM

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 

pirates-of-the-caribbean-johnny-depp

- [ ] As I can see one member committed only to the README file, but make sure all of you   contributed equally to the project


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by M-AminAlizadeh** [comment]
@abdulhamiid  Thank you for the CR
But according to the requirements, my partner added the commit 
Screenshot 2023-11-18 021834

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi Team 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🧧 
 This milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#work-and-submission-mode).

I noticed @RicardoEgas  only made changes to the README, which does not count for the skills that is been tested in adding devise.  Please ensure that your partner has a significant contribution and everyone has contributed equally to the project you're reviewing. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by Shedrack-Sunday** [comment]
Hello @M-AminAlizadeh , We did not ignore it. From the email Marcos wrote, it shows 3 persons where in your team. Pushhar was permitted to leave the group, but as i said in the invalidaion, @RicardoEgas one commit on the README does not count. It has to be a contribution to the codebase

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi Team 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid Code Review Request 🧧
This milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#work-and-submission-mode).

I noticed @RicardoEgas only made changes to the README, which does not count for the skills that is been tested in adding devise. Student success only allowed one team member @Pushkar to leave the team, which means @RicardoEgas's commit on the code should be present. Please ensure that your partner has a significant contribution and everyone has contributed equally to the project you're reviewing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by M-AminAlizadeh** [comment]
I do more commits than my partners because I wadsthe driver and he was the navigator
And want to learn more about devise

**Review by DeliceLydia — APPROVED** [review]
## Hi @M-AminAlizadeh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Highlights
- The application asks for confirmation of email.
- A user can reset the password in the application.
- A hashed password is stored in the database.



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DeliceLydia** [comment]
@M-AminAlizadeh Please next time to contribute equally to the project

**Comment by M-AminAlizadeh** [comment]
I do more commits than my partners because I wadsthe driver and he was the navigator
And want to learn more about devise

**Comment by M-AminAlizadeh** [comment]
> @M-AminAlizadeh Please next time contribute equally to the project with your partner

@DeliceLydia thank you sure I will

**Pull request merged**
